-- Example test file using plenary.nvim
local list = require("list")

describe("list.nvim", function()
  describe("setup", function()
    it("can be required", function()
      assert(list ~= nil)
    end)

    it("has setup function", function()
      assert(type(list.setup) == "function")
    end)
  end)

  describe("detect_list_format", function()
    it("detects bullet list with dash", function()
      local result = list.detect_list_format("- item")
      assert(result ~= nil)
      assert(result.type == "bullet")
      assert(result.marker == "-")
      assert(result.indent == 0)
    end)

    it("detects bullet list with asterisk", function()
      local result = list.detect_list_format("* item")
      assert(result ~= nil)
      assert(result.type == "bullet")
      assert(result.marker == "*")
      assert(result.indent == 0)
    end)

    it("detects ordered list", function()
      local result = list.detect_list_format("1. item")
      assert(result ~= nil)
      assert(result.type == "ordered")
      assert(result.number == 1)
      assert(result.indent == 0)
    end)

    it("detects checkbox unchecked", function()
      local result = list.detect_list_format("- [ ] item")
      assert(result ~= nil)
      assert(result.type == "checkbox")
      assert(result.checked == false)
      assert(result.indent == 0)
    end)

    it("detects checkbox checked", function()
      local result = list.detect_list_format("- [x] item")
      assert(result ~= nil)
      assert(result.type == "checkbox")
      assert(result.checked == true)
      assert(result.indent == 0)
    end)

    it("detects indented list", function()
      local result = list.detect_list_format("    - item")
      assert(result ~= nil)
      assert(result.type == "bullet")
      assert(result.marker == "-")
      assert(result.indent == 4)
    end)

    it("returns nil for non-list line", function()
      local result = list.detect_list_format("regular text")
      assert(result == nil)
    end)
  end)

  describe("auto_continue_list", function()
    before_each(function()
      vim.api.nvim_command("enew!")
      vim.bo.filetype = "markdown"
    end)

    it("continues bullet list with dash", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "- item" })
      vim.api.nvim_win_set_cursor(0, { 1, 6 })
      list.auto_continue_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[2] == "- ")
    end)

    it("continues bullet list with asterisk", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "* item" })
      vim.api.nvim_win_set_cursor(0, { 1, 6 })
      list.auto_continue_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[2] == "* ")
    end)

    it("continues ordered list with incremented number", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "1. item" })
      vim.api.nvim_win_set_cursor(0, { 1, 7 })
      list.auto_continue_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[2] == "2. ")
    end)

    it("continues checkbox unchecked", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "- [ ] item" })
      vim.api.nvim_win_set_cursor(0, { 1, 10 })
      list.auto_continue_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[2] == "- [ ] ")
    end)

    it("preserves indentation", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "    - item" })
      vim.api.nvim_win_set_cursor(0, { 1, 10 })
      list.auto_continue_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[2] == "    - ")
    end)

    it("removes empty list item", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "- " })
      vim.api.nvim_win_set_cursor(0, { 1, 2 })
      list.auto_continue_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "")
      assert(lines[2] == "")
    end)

    it("does nothing on non-list line", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "regular text" })
      vim.api.nvim_win_set_cursor(0, { 1, 12 })
      list.auto_continue_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "regular text")
      assert(lines[2] == "")
    end)
  end)
end)
