-- Test file for normal mode operations (o and O)
local list = require("list")

describe("normal mode operations", function()
  before_each(function()
    vim.api.nvim_command("enew!")
    vim.bo.filetype = "markdown"
  end)

  describe("open_below_with_list", function()
    it("continues bullet list with dash", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "- item" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      list.open_below_with_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "- item")
      assert(lines[2] == "- ")
    end)

    it("continues bullet list with asterisk", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "* item" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      list.open_below_with_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "* item")
      assert(lines[2] == "* ")
    end)

    it("continues ordered list with incremented number", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "1. item" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      list.open_below_with_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "1. item")
      assert(lines[2] == "2. ")
    end)

    it("continues checkbox unchecked", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "- [ ] item" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      list.open_below_with_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "- [ ] item")
      assert(lines[2] == "- [ ] ")
    end)

    it("preserves indentation", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "    - item" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      list.open_below_with_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "    - item")
      assert(lines[2] == "    - ")
    end)

    it("falls back to normal 'o' on non-list line", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "regular text" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      list.open_below_with_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "regular text")
      assert(lines[2] == "")
    end)
  end)

  describe("open_above_with_list", function()
    it("continues bullet list with dash", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "- item" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      list.open_above_with_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "- ")
      assert(lines[2] == "- item")
    end)

    it("continues bullet list with asterisk", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "* item" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      list.open_above_with_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "* ")
      assert(lines[2] == "* item")
    end)

    it("continues ordered list with same number", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "2. item" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      list.open_above_with_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "2. ")
      assert(lines[2] == "2. item")
    end)

    it("continues checkbox unchecked", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "- [ ] item" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      list.open_above_with_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "- [ ] ")
      assert(lines[2] == "- [ ] item")
    end)

    it("preserves indentation", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "    - item" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      list.open_above_with_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "    - ")
      assert(lines[2] == "    - item")
    end)

    it("falls back to normal 'O' on non-list line", function()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "regular text" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      list.open_above_with_list()
      local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
      assert(#lines == 2)
      assert(lines[1] == "")
      assert(lines[2] == "regular text")
    end)
  end)
end)
